# Generated by Django 6.0.2 on 2026-02-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_shop_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
