# Generated by Django 6.0.2 on 2026-03-01 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_offer_image_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='api.shop'),
        ),
    ]
